// var scale_list = {
//   "0":["awful vs. nice", 
//   "little vs. big", 
//   "slow vs. fast",
//   "sour vs. sweet",
//   "powerless vs. poweful",
//   "quiet vs. noisy"],
//   "1":[
//   "hellish vs. heavenly",
//   "shallow vs. deep",
//   "old vs. young",
//   "bad vs. good",
//   "weak vs. strong", 
//   "dead vs. alive",
//   ],
//   "2":[
//   "mild vs. harsh",
//   "low vs. high",
//   "unknown vs. known",
//   "sad vs. happy",
//   "short vs. long",
//   "freezing vs. burning"
//   ],
// }
var scale_list = {
"0":[
"ugly vs. beautiful", 
"yellow vs. blue",
"hard vs. soft",
"dirty vs. clean", 
"agitated vs. calm", 
"distasteful vs. tasty"],
"1":[ 
"worthless vs. valuable", 
"red vs. green" ,
"cruel vs. kind" ,
"soft vs. loud" ,
"unpleasant vs. pleasant", 
"black vs. white" ],
"2":[
"bitter vs. sweet",
"dull vs. sharp" ,
"empty vs. full" ,
"ferocious vs. peaceful",
"light vs. heavy" ,
"dry vs. wet" ],
"3":[
"profane vs. sacred" ,
"tense vs. relaxed" ,
"cowardly vs. brave" ,
"poor vs. rich" ,
"hazy vs. clear" ,
"thin vs. thick" ],
"4":[
"dark vs. bright" ,
"treble vs. bass" ,
"rounded vs. angular", 
"foul vs. fragrant" ,
"passive vs. active" ,
"smooth vs. rough" ],
"5":[
"stale vs. fresh" ,
"unfair vs. fair" ,
"delicate vs. rugged", 
"bland vs. pungent" ,
"sick vs. healthy" ,
"narrow vs. wide"]
}





// var concept_list = [
//   'bear',
//   'bird',
//   'lion',
//   'frog',
//   'fish',
//   'airplane',
//   'car',
//   'boat',
//   'truck',
//   'train',
//   'apple',
//   'banana',
//   'cherry',
//   'grape',
//   'peach',
//   'carrot',
//   'celery',
//   'corn',
//   'eggplant',
//   'mushroom',
//   'blizzard',
//   'drought',
//   'hurricane',
//   'lightning',
//   'sandstorm',
//   'evil',
//   'greed',
//   'justice',
//   'love',
//   'peace',
//   'driving',
//   'eating',
//   'sleeping',
//   'leisure',
//   'working',
//   'comfort',
//   'efficiency',
//   'speed',
//   'safety',
//   'reliability'
// ]


var concept_list = [
  'dress',
  'pants',
  'shirt',
  'socks',
  'shoes',
  'blueberry',
  'lemon',
  'mango',
  'strawberry',
  'watermelon',
  'beach',
  'field',
  'ocean',
  'sky',
  'sunset',
  'angry',
  'disgust',
  'fearful',
  'happy',
  'sad',
  'above',
  'below',
  'beside',
  'near',
  'far',
  'dawn',
  'day',
  'dusk',
  'night',
  'noon',
]